# Generated by Django 3.2.5 on 2021-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Article text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Article title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment text',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='', verbose_name='Article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Article title'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='Comment author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='Comment text'),
        ),
    ]
